#!/usr/bin/env bash
# Maintainer: joekamprad [joekamprad //a_t// endeavouros.com]
git clone https://github.com/ringo32/swayi3.git
cd swayi3/etc/skel/
cp -R .config ~/
chmod -R +x ~/.config/sway/scripts
cp .Xresources .profile xed.dconf ~/
dbus-launch dconf load / < ~/xed.dconf
rm xed.dconf
cd ..
rm -rf endeavouros-i3wm-setup
wget https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-packages-lists/master/i3
sudo pacman -S --needed - < sway
rm sway
#eos-packagelist --install "i3-Window-Manager"
